name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pull theme repo
      run: git clone https://github.com/Parbhat/pelican-blue.git themes/pelican-blue
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
